# Generated by Django 6.0.3 on 2026-03-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stationreview'),
    ]

    operations = [
    ]
